# Spring配置
spring:
  config:
    activate:
      on-profile: prod
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://mysql:3306/project_management?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: ENC(V/+BNSSw11lfJV0fuKLFOWgPAsvFRV/iLicyDF+SBytXAXZIvHbIzaj4yHi36HlffqOzcCedxFzVh6sy7Xf4fg==)
        password: ENC(LTxR/t2yuTaqAAKMlB21j00YSRmWm+2UDBPfpdw2K9PaQYoto4OYFE21HMCEV9uJdoWLqSuaxNTJAKaVddrw/Hj6zC33X5Oy5JoNiadf5DLmvZurvyw+HS2Zm/pbVVK33OrgYsZhZL3DHoHv5v4xIg==)
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: xiaofei
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    # 地址
    host: redis7
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 15
    # 密码
    password: ENC(jj1Mhvoh5C/pglB6QMk6Lh0YFPfAwm8a1NIuJDUfBx74YWx+c0UpM6yi7kvixHk8cKSsSwSVOYI8W9TNmV5ZeTiDx8Qv3YhyZSKcXaJcjVM=)
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
# 接口地址服务地址
gatewayUrl: ENC(uisc3y179XVYunMq8Ia7PTKzFFX6AywBYdCz1OhN5H2/ZPG1AiW6S07Ok85/w2yTiu8kB2Uj/LxKG24kNz0WK31TkTUxgHy6RgJ7EgKE2rQ=)
dubbo:
  provider:
    timeout: 5000
  application:
    name: project-management
  registry:
    address: nacos://nacos:8848
    # 命名空间配置
    parameters:
      namespace: e3387225-0718-4b40-8259-8526a60311ba